Tourist_VietripInsum_2023/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Tourist_VietripInsum_2023.common;
using Tourist_VietripInsum_2023.Models;
using PagedList;
using System.Web.Routing;
using System.Text.RegularExpressions;
using Tourist_VietripInsum_2023.DesignPattern.Singleton;
using Tourist_VietripInsum_2023.DesignPattern.Repository;
using Tourist_VietripInsum_2023.DesignPattern.TemplateMethod;
using System.Diagnostics;

namespace Tourist_VietripInsum_2023.Controllers
{
    public class GuestController : TemplateMethodController
    {
        TouristEntities1 db = new TouristEntities1();
        IBaseRepository _guestRepository = new BaseRepository();
        public GuestController()
        {
            UserLogedInSingleton<KhachHang>.Instance.InitSingleton(db);

            //implement template method
            var result = PrintInfo();
            Debugger.Log(1, "Logger: ", $"{result}");
        }

        // GET: Guest

        public ActionResult HomePageGuest()
        {
            return View();
        }
        
        private List<DiaDiemThamQuan> Lay_DiaDiem()
        {
            List<DiaDiemThamQuan> diaDiemThamQuans = db.DiaDiemThamQuans.ToList();
            List<ChiTietTour> chiTietTours = db.ChiTietTours.ToList();
            List<Tour> tourChon = db.Tours.Where(n=>n.TrangThai!="Sắp ra mắt").ToList();

            var bangchon = (from diadiem in diaDiemThamQuans
                            join chitiet in chiTietTours on diadiem.MaDDTQ equals chitiet.MaDDTQ
                            join tour in tourChon on chitiet.MaTour equals tour.MaTour
                            group chitiet by chitiet.MaDDTQ into g
                            select new
                            {
                                MaDD = g.FirstOrDefault().MaDDTQ,
                                Matour= g.FirstOrDefault().MaTour

                            }).ToList();

            List<DiaDiemThamQuan> d = new List<DiaDiemThamQuan>();

            foreach (var i in bangchon)
            {
                var item = db.DiaDiemThamQuans.Where(m => m.MaDDTQ == i.MaDD).FirstOrDefault();
               d.Add(item);

            }
            return d;
        }
        public ActionResult DiaDiemTour()
        {
            List<DiaDiemThamQuan> diadiemtim = Lay_DiaDiem();
            return PartialView(diadiemtim);
        }
        public ActionResult DiaDiemPartial()
        {
            List<DiaDiemThamQuan> diaDiemThamQuans = db.DiaDiemThamQuans.ToList();
            List<ChiTietTour> chiTietTours = db.ChiTietTours.ToList();
            List<Tour> tourChon = db.Tours.Where(n => n.TrangThai != "Sắp ra mắt").ToList();

            var bangtinh = (from diadiem in diaDiemThamQuans
                            join chitiet in chiTietTours on diadiem.MaDDTQ equals chitiet.MaDDTQ
                            join tour in tourChon on chitiet.MaTour equals tour.MaTour
                            group diadiem by diadiem.MaTinh into g
                            select new
                            {
                                MaTinh = g.FirstOrDefault().MaTinh,
                            }).ToList();

            List<TinhThanh> tinhtour = new List<TinhThanh>();

            foreach (var i in bangtinh)
            {
                var item = db.TinhThanhs.Where(m => m.MaTinh == i.MaTinh).FirstOrDefault();
                tinhtour.Add(item);
            }

            return PartialView(tinhtour);
        }

        public ActionResult Tourinfomation(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tour tour = db.Tours.Where(s => s.MaTour == id).FirstOrDefault();
            Session["Matourchon"] = id;
            if (tour == null)
            {
                return HttpNotFound();
            }
            Session["mat"]=id;
            return View(tour);
        }

        //List tour tinh thanh

       
        private List<Tour> lay_Tour(string id)
        {
            List<Tour> tour = new List<Tour>();
            List<ChiTietTour> ct = db.ChiTietTours.Where(c => c.MaDDTQ == id).ToList();
            foreach (var item in ct)
            {
                
                var tourchon = db.Tours.Where(t => t.MaTour == item.MaTour).FirstOrDefault();
                if(tourchon.TrangThai!="Sắp ra mắt")
                {
                    tour.Add(tourchon);
                }    
                
            }
            return tour;
        }
       
        public ActionResult ListTourTinhThanh(string id,int? page)
        {
            
            List<Tour> tour = new List<Tour>();
            List<DiaDiemThamQuan> diaDiems = db.DiaDiemThamQuans.ToList();
            List<ChiTietTour> chiTietTours = db.ChiTietTours.ToList();
            List<Tour> tours = db.Tours.ToList();
            Session["tentinh"] = id;
            var tinhthanh = (from s in diaDiems

                            join a in chiTietTours on s.MaDDTQ equals a.MaDDTQ
                            where s.MaTinh==id
                            group a by a.MaTour into g
                            select new
                            {
                                MaTour = g.FirstOrDefault().MaTour,

                            }).ToList();
            
            foreach (var item in tinhthanh)
            {
                var a = db.Tours.Where(s => s.MaTour == item.MaTour).FirstOrDefault();
                if(a.TrangThai!="Sắp ra mắt" && a.SoChoNull>0 && a.HanChotDatVe>DateTime.Today)
                {
                    tour.Add(a);
                }    
                
            }
            int pageSize = 9;
            int pageNum = (page ?? 1);
            return View(tour.ToPagedList(pageNum,pageSize));
        }

        [HttpPost]
        public ActionResult ListTourTinhThanh(string trangthai, int? page, string noikhoihanh, string songay, string ngaykhoihanh, string songuoi, int? songaybd, int? songaykt, int? songuoibd)
        {
            //Xử lý số ngày, số người, ngày khơi hành
            if (songay == "1 - 3 ngày")
            {
                songaybd = 1;
                songaykt = 3;
            }
            else if (songay == "4 - 7 ngày")
            {
                songaybd = 4;
                songaykt = 7;
            }
            else if (songay == "8 - 10 ngày")
            {
                songaybd = 8;
                songaykt = 10;
            }
            else if (songay == "10+ ngày")
            {
                songaybd = 10;
                songaykt = 100;
            }
            //--------------------
            if (songuoi == "1 người")
            {
                songuoibd = 1;
            }
            else if (songuoi == "2 - 3 người")
            {
                songuoibd = 2;
            }
            else if (songuoi == "3 - 5 người")
            {
                songuoibd = 3;
            }
            else if (songuoi == "5+ người")
            {
                songuoibd = 5;
            }
            //ngaykhoihanh = String.Format("{0:d/M/yyyy}", tour.NgayKhoihanh);
            DateTime.Now.ToString("yyyy-MM-dd");
            int pageSize = 9;
            int pageNum = (page ?? 1);
            List<Tour> toura = new List<Tour>();
            List<DiaDiemThamQuan> diaDiems = db.DiaDiemThamQuans.ToList();
            List<ChiTietTour> chiTietTours = db.ChiTietTours.ToList();
            List<Tour> dstours = db.Tours.ToList();
            string id = (string)Session["tentinh"];
            var tinhthanh = (from s in diaDiems

                             join a in chiTietTours on s.MaDDTQ equals a.MaDDTQ
                             where s.MaTinh == id
                             group a by a.MaTour into g
                             select new
                             {
                                 MaTour = g.FirstOrDefault().MaTour,

                             }).ToList();

            foreach (var item in tinhthanh)
            {
                var a = db.Tours.Where(s => s.MaTour == item.MaTour).FirstOrDefault();
                if (a.TrangThai != "Sắp ra mắt" && a.SoChoNull > 0 && a.HanChotDatVe>DateTime.Today)
                {
                    toura.Add(a);
                }

            }
            if (noikhoihanh == "---Tất cả---")
            {
                var toursearchall = toura.ToList();
                var toursall = toursearchall.ToPagedList(pageNum, pageSize);
                return View(toursall);
            }
            //List<Tour> tour = Lay_DiaDiem();
            var toursearch = toura.Where(s => s.NoiKhoiHanh == noikhoihanh && (s.SoNgay >= songaybd && s.SoNgay <= songaykt) && s.SoChoNull >= songuoibd).ToList();
            var tours = toursearch.ToPagedList(pageNum, pageSize);
            return View(tours);
        }




        //dia danh

        public ActionResult ListTour_DiaDiem(string id,int? page)
        {
            if (id != null)
            {
                Session["madiadiem"] = id;
                var iddiadiem = db.DiaDiemThamQuans.Where(d => d.MaDDTQ == id).FirstOrDefault();
                List<Tour> tour = lay_Tour(id);
                int pageSize = 9;
                int pageNum = (page ?? 1);
                Session["tendiadiem"] = iddiadiem.TenDDTQ;
                return View(tour.ToPagedList(pageNum, pageSize));
            }
            else
            {
                id = (string)Session["madiadiem"];
                var iddiadiem = db.DiaDiemThamQuans.Where(d => d.MaDDTQ == id).FirstOrDefault();
                List<Tour> tour = lay_Tour(id);
                int pageSize = 9;
                int pageNum = (page ?? 1);
                Session["tendiadiem"] = iddiadiem.TenDDTQ;

Tourist_VietripInsum_2023/Views/Guest/ViewGuest/Guest.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.title</title>
    @Scripts.Render("~/bundles/jquery")
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- icon boxicons  -->
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">

    <!-- custom css file link  -->

    <link href="~/Content/Guest/StyleGuest.css" rel="stylesheet" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>





</head>
<body>
    <div>
        <!-- header section starts  -->
        <header class="header">
            <nav class="navbar navbar-expand-lg " style="background: #094933 ">
                <div class="container-fluid">
                    <a class="navbar-brand " href="/Guest/HomePageGuest">
                        <img src="~/Content/Images/logo_project.png" height="40" width="30px" />
                        <span>SAIGON TRAVELS</span>
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <!-- Mega Menu -->
                            <li class="nav-item dropdown has-megamenu">
                                <a class="nav-link dropdown-toggle  @ViewBag.mn" href="#" data-bs-toggle="dropdown"> Du lịch </a>
                                <div class="dropdown-menu megamenu" role="menu">
                                    @Html.Action("DiaDiemPartial", "Guest")
                                </div> <!-- dropdown-mega-menu.// -->
                            </li>

                            <li class="nav-item">
                                <a class="nav-link @ViewBag.tt" href="~/Guest/TinTuc" role="button" aria-expanded="false">
                                    Tin tức
                                </a>
                            </li>
                            @*<li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Tin tức
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li><a class="dropdown-item" href="/tin-moi.aspx">Tin mới</a></li>
                                        <li><a class="dropdown-item" href="/tin-tuc-du-lich.aspx">Tin tức du lịch</a></li>
                                        <li><a class="dropdown-item" href="/du-lich-bang-hinh-anh.aspx">Cẩm nang du lịch</a></li>
                                        <li><a class="dropdown-item" href="/kinh-nghiem-du-lich.aspx">Kinh nghiệm du lịch</a></li>
                                    </ul>
                                </li>*@
                            @*<li class="nav-item">
                                    <a class="nav-link" href="#home-page_listtour">Tour Nổi Bật</a>
                                </li>*@
                            <li class="nav-item">
                                <a class="nav-link @ViewBag.lh" href="~/Guest/LienHeGuest">Liên Hệ</a>
                            </li>
                            @*<li class="nav-item">
                                    <a class="nav-link" href="#"></a>
                                </li>*@
                        </ul>
                        @*<form class="d-flex">
                                <input class="search-mn form-control me-2" type="search" placeholder="Search" aria-label="Search">
                                <button class="btn btn-outline-success btnsearchdetail" type="submit">Search</button>
                            </form>
                            <div class="group-features">
                                <div class="account item">
                                    <a href="">
                                        <i class="fas fa-user"></i>
                                    </a>
                                </div>
                            </div>*@
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                @{ var user = (Tourist_VietripInsum_2023.Models.KhachHang)HttpContext.Current.Session["UserKH"];}
                                @if (user == null)
                                {
                                    <a style="padding-left: 150px;" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        <img class="img-circle" src="~/images/user.png" style="border-radius: 100%" width="30" height="30" />
                                    </a>
                                }
                                else
                                {
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        <span style="color: white;">Hello, @user.HoTenKH</span>
                                        @if (user.HinhDaiDien == null)
                                        {
                                            <img class="img-circle" src="~/images/user.png" style="margin-left: 5px; border-radius: 100%" width="30" height="30" />
                                        }
                                        else
                                        {
                                            <img class="img-circle" src="~/images/@user.HinhDaiDien" style="margin-left: 5px; border-radius: 100%" width="30" height="30" />
                                        }
                                    </a>
                                }
                                @if (user == null)
                                {
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li><a class="dropdown-item" href="~/Guest/LoginGuest">Đăng nhập</a></li>
                                        <li><a class="dropdown-item" href="~/Guest/SignupGuest">Đăng ký</a></li>
                                    </ul>
                                }
                                else
                                {
                            <ul style="margin-left: 50px;" class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="~/Guest/Thongtinkhachhang/@user.MaKH">Thông tin cá nhân</a></li>
                                <li><a class="dropdown-item" href="~/Guest/LogOut">Đăng xuất</a></li>
                            </ul>
                                }
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <!-- header section ends -->
    </div>

    <div>
        @RenderBody()
        <!-- Start of LiveChat (www.livechat.com) code -->
        <!--<script>
        window.__lc = window.__lc || {};
        window.__lc.license = 15360669;
        ; (function (n, t, c) { function i(n) { return e._h ? e._h.apply(null, n) : e._q.push(n) } var e = { _q: [], _h: null, _v: "2.0", on: function () { i(["on", c.call(arguments)]) }, once: function () { i(["once", c.call(arguments)]) }, off: function () { i(["off", c.call(arguments)]) }, get: function () { if (!e._h) throw new Error("[LiveChatWidget] You can't use getters before load."); return i(["get", c.call(arguments)]) }, call: function () { i(["call", c.call(arguments)]) }, init: function () { var n = t.createElement("script"); n.async = !0, n.type = "text/javascript", n.src = "https://cdn.livechatinc.com/tracking.js", t.head.appendChild(n) } }; !n.__lc.asyncInit && e.init(), n.LiveChatWidget = n.LiveChatWidget || e }(window, document, [].slice))
    </script>
    <noscript><a href="https://www.livechat.com/chat-with/15360669/" rel="nofollow">Chat with us</a>, powered by <a href="https://www.livechat.com/?welcome" rel="noopener nofollow" target="_blank">LiveChat</a></noscript>-->
        <!-- End of LiveChat code merge-->

        <!-- Start of LiveChat (www.livechat.com) code -->
        <script>
            window.__lc = window.__lc || {};
            window.__lc.license = 15440004;
            ; (function (n, t, c) { function i(n) { return e._h ? e._h.apply(null, n) : e._q.push(n) } var e = { _q: [], _h: null, _v: "2.0", on: function () { i(["on", c.call(arguments)]) }, once: function () { i(["once", c.call(arguments)]) }, off: function () { i(["off", c.call(arguments)]) }, get: function () { if (!e._h) throw new Error("[LiveChatWidget] You can't use getters before load."); return i(["get", c.call(arguments)]) }, call: function () { i(["call", c.call(arguments)]) }, init: function () { var n = t.createElement("script"); n.async = !0, n.type = "text/javascript", n.src = "https://cdn.livechatinc.com/tracking.js", t.head.appendChild(n) } }; !n.__lc.asyncInit && e.init(), n.LiveChatWidget = n.LiveChatWidget || e }(window, document, [].slice))
        </script>
        <noscript><a href="https://www.livechat.com/chat-with/15440004/" rel="nofollow">Chat with us</a>, powered by <a href="https://www.livechat.com/?welcome" rel="noopener nofollow" target="_blank">LiveChat</a></noscript>
        <!-- End of LiveChat code -->

    </div>
    @RenderSection("script", false)
    <!-- footer section  -->

    <div>
        <div class="footerguest">
            <div class="container">

                <div class="footer-content row">
                    <div class="col-sm-6">
                        <h2>CÔNG TY CỔ PHẦN THƯƠNG MẠI DU LỊCH SAIGON TRAVEL</h2>
                        <p>MST: 1801511350. Ngày cấp giấy phép: 24/01/2017</p>
                        <p>VP HCM chi nhánh Q3: 10 Hai Bà Trưng, Q.3, TP.HCM</p>
                        <p>VP HCM chi nhánh Q1: 45 Đinh Tiên Hoàng, P. Bến Nghé, Q1, TP. HCM</p>
                        <p>VP Hà Nội: 123 Cầu Giấy, Quận Hoàn Kiếm, Hà Nội</p>

                    </div>
                    <div class="col-sm-3">
                        <h2>LIÊN HỆ</h2>
                        <p>
                            <a href="#">(+84 28) 1234 2345</a>
                        </p>
                        <p>
                            <a href="#">(+84 28) 1234 2345</a>
                        </p>
                        <P>
                            <a href="#">info@saigontravel.com</a>
                        </P>

                    </div>

                    <div class="col-sm-3">
                        <h2>LIÊN KẾT</h2>
                        <p>
                            <a href="#">Trang Facebook</a>
                        </p>
                        <p>
                            <a href="#">Instagram</a>
                        </p>
                        <P>
                            <a href="#">Twitter</a>
                        </P>

                    </div>

                </div>
            </div>
        </div>
    </div>
</body>
</html>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<script src="~/Content/Guest.js"></script>

Tourist_VietripInsum_2023/Views/Guest/ViewGuest/customer_info.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    @Scripts.Render("~/bundles/jquery")
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- icon boxicons  -->
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">

    <!-- custom css file link  -->
    <link href="~/Content/Guest/info-customer.css" rel="stylesheet" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>



</head>
<body>
    @{ var user = (Tourist_VietripInsum_2023.Models.KhachHang)HttpContext.Current.Session["UserKH"];}
    <div>
        <!-- header section starts  -->
        <header class="header">
            <nav class="navbar navbar-expand-lg " style="background: #094933 ">
                <div class="container-fluid">
                    <a class="navbar-brand" href="/Guest/HomePageGuest">
                        <img src="~/Content/Images/logo_project.png" height="40" width="30" />
                        <span>SAIGON TRAVELS</span>
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <!-- Mega Menu -->
                            <li class="nav-item dropdown has-megamenu">
                                <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown"> Du lịch </a>
                                <div class="dropdown-menu megamenu" role="menu">
                                    @Html.Action("DiaDiemPartial", "Guest")
                                </div> <!-- dropdown-mega-menu.// -->
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="~/Guest/TinTuc" role="button" aria-expanded="false">
                                    Tin tức
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="~/Guest/LienHeGuest">Liên Hệ</a>
                            </li>

                        </ul>


                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">

                                @if (user == null)
                                {
                                    <a style="padding-left: 150px;" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        <img class="img-circle" src="~/images/user.png" style="border-radius: 100%" width="30" height="30" />
                                    </a>
                                }
                                else
                                {
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        <span style="color: white;">Hello, @user.HoTenKH</span>
                                        @if (user.HinhDaiDien == null)
                                        {
                                            <img class="img-circle" src="~/images/user.png" style="margin-left: 5px; border-radius: 100%" width="30" height="30" />
                                        }
                                        else
                                        {
                                            <img class="img-circle" src="~/images/@user.HinhDaiDien" style="margin-left: 5px; border-radius: 100%" width="30" height="30" />
                                        }
                                    </a>
                                }
                                @if (user == null)
                                {
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li><a class="dropdown-item" href="~/Guest/LoginGuest">Đăng nhập</a></li>
                                        <li><a class="dropdown-item" href="~/Guest/SignupGuest">Đăng ký</a></li>
                                    </ul>
                                }
                                else
                                {
                                    <ul style="margin-left: 50px;" class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li><a class="dropdown-item" href="~/Guest/Thongtinkhachhang/@user.MaKH">Thông tin cá nhân</a></li>
                                        <li><a class="dropdown-item" href="~/Guest/LogOut">Đăng xuất</a></li>
                                    </ul>
                                }
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <!-- header section ends -->
    </div>
    <div class="body">
        <div class="container">
            <div class="thongtinkh">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="hero-text">
                            <div class="infocus">
                                <div class="img text-center mb-3">
                                    <img style="width: 100px;height: 100px;border-radius: 50%" src="~/images/@user.HinhDaiDien" alt="Image">
                                </div>
                                <h4><b>@user.HoTenKH</b> </h4>
                            </div>
                            <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                            </div>
                            <div class="menu-func">
                                <h4>Tài khoản </h4>
                                <nav class="navbar bg-success navbar-light" style="border-radius:10px ">
                                    <div class="container-fluid">
                                        <ul class="navbar-nav">
                                            <li class="nav-item">
                                                <a class="nav-link @ViewBag.ttcn" href="/Guest/Thongtinkhachhang/@user.MaKH">Thông tin cá nhân</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link @ViewBag.ls " href="/Guest/TourBookingHistory">Lịch sử đơn hàng</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link @ViewBag.ddh"  href="/Guest/NewOrderPlaced">Đơn đặt chỗ</a>
                                            </li>
                                        </ul>
                                    </div>
                                </nav>
                            </div>


                        </div>

                    </div>
                    <div class="col-sm-8">
                        <div class="content-cus">
                            @RenderBody()
                            <!-- Start of LiveChat (www.livechat.com) code -->
                            <script>
                                window.__lc = window.__lc || {};
                                window.__lc.license = 15360669;
                                ; (function (n, t, c) { function i(n) { return e._h ? e._h.apply(null, n) : e._q.push(n) } var e = { _q: [], _h: null, _v: "2.0", on: function () { i(["on", c.call(arguments)]) }, once: function () { i(["once", c.call(arguments)]) }, off: function () { i(["off", c.call(arguments)]) }, get: function () { if (!e._h) throw new Error("[LiveChatWidget] You can't use getters before load."); return i(["get", c.call(arguments)]) }, call: function () { i(["call", c.call(arguments)]) }, init: function () { var n = t.createElement("script"); n.async = !0, n.type = "text/javascript", n.src = "https://cdn.livechatinc.com/tracking.js", t.head.appendChild(n) } }; !n.__lc.asyncInit && e.init(), n.LiveChatWidget = n.LiveChatWidget || e }(window, document, [].slice))
                            </script>
                            <noscript><a href="https://www.livechat.com/chat-with/15360669/" rel="nofollow">Chat with us</a>, powered by <a href="https://www.livechat.com/?welcome" rel="noopener nofollow" target="_blank">LiveChat</a></noscript>
                            <!-- End of LiveChat code merge-->
                        </div>
                            @RenderSection("scripts", false)
                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>
 






</body>
</html>