Tourist_VietripInsum_2023/Controllers/OrderProcessingController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Tourist_VietripInsum_2023.App_Start;
using Tourist_VietripInsum_2023.common;
using Tourist_VietripInsum_2023.DesignPattern.Singleton;
using Tourist_VietripInsum_2023.DesignPattern.TemplateMethod;
using Tourist_VietripInsum_2023.Models;

namespace Tourist_VietripInsum_2023.Controllers
{
    [AdminAuthorize(idPos = "OP")]
    public class OrderProcessingController : TemplateMethodController
    {
        TouristEntities1 db = new TouristEntities1();

        public OrderProcessingController()
        {
            var result = PrintInfo();
            Debugger.Log(1, "Logger: ", $"{result}");
        }

        public ActionResult HomePageOP()
        {
            var donhang = db.BookTours.Count();
            TempData["TongDonDat"] = donhang;
            var ph = db.PhanHois.Count(s => s.TieuDe == "Tư vấn đơn đặt tour");
            TempData["phanhoi"] = ph;
            var dsDonHangMoi = db.BookTours.OrderByDescending(dhang => dhang.NgayLap).ToList();
        
            return View(dsDonHangMoi);
        }

        public ActionResult ManageTourOrders(string search)
        {
            if (search == null)
            {
                return View(db.BookTours.ToList());
            }
            else
            {
                ViewBag.SearchInfo = search;
                return View(db.BookTours.Where(s => s.MaDH.ToLower().Contains(search) == true || s.SdtKH.ToLower().Contains(search) == true).ToList());
            }
        }

        public ActionResult TourList()
        {
            List<Tour> listTour = db.Tours.Include(t => t.LoaiTour).Where(s=>s.TrangThai!="Sắp ra mắt").ToList();
            return View(listTour);
        }

        public ActionResult CusDetailsTour(string id)
        {
            TempData["MaTour"] = id;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            List<BookTour> booking = db.BookTours.Where(s => s.MaTour == id).ToList();
            List<Ve> ve = new List<Ve>();
            foreach (var i in booking)
            {
                var maDH = i.MaDH;
                ve = db.Ves.Where(s => s.MaDH == maDH).ToList();
            }
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(ve);
        }

        public ActionResult ListOfCustomers(string search)
        {
            if (search == null)
            {
                return View(db.KhachHangs.ToList());
            }
            else
            {
                return View(db.KhachHangs.Where(s => s.MaKH.ToLower().Contains(search) == true || s.SDT.ToLower().Contains(search) == true || s.HoTenKH.ToLower().Contains(search) == true).ToList());
            }
        }

        public ActionResult CusDetail(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            KhachHang khachHang = db.KhachHangs.Find(id);

            if (id == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        public ActionResult EditCusInfo(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = db.KhachHangs.Find(id);
            Session["maKH"] = id;
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoaiKH = new SelectList(db.LoaiKHs, "MaLoaiKH", "TenLoaiKH", khachHang.MaLoaiKH);
            return View(khachHang);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCusInfo(KhachHang kh)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kh).State = EntityState.Modified;
                db.SaveChanges();

                var bookTour = db.BookTours.Where(s => s.MaKH == kh.MaKH).ToList();
                foreach (var item in bookTour)
                {
                    item.SdtKH = kh.SDT;
                    db.Entry(item).State = System.Data.Entity.EntityState.Modified;
                }
                db.SaveChanges();
                TempData["success"] = "Cập nhật thông tin khách hàng thành công";
                return RedirectToAction("ListOfCustomers");
            }
            ViewBag.LoaiKH = new SelectList("MaLoaiKH", "MaLoaiKH", kh.MaLoaiKH);
            return View(kh);
        }

        public ActionResult CheckCusInfo(string search)
        {
            var info = db.KhachHangs.FirstOrDefault(s => s.SDT == search);
            if (search == null)
            {
                return View();
            }
            else
            {
                if (info == null)
                {
                    ViewBag.Info = info;
                    ViewBag.SDT = search;
                    Session["SDT"] = search;
                    return View();
                }
                else
                {
                    ViewBag.Info = info;
                    ViewBag.SDT = search;
                    Session["SDT"] = search;
                    return View(info);
                }
            }
        }
        [HttpPost, ActionName("CheckCusInfo")]
        public ActionResult CreateCustomer([Bind(Include = "MaKH,SDT,MaLoaiKH,Username,UserPassword,HoTenKH,DiaChi,Email,NgaySinh,GioiTinh,HinhDaiDien")] KhachHang khachHang)
        {
            Random random = new Random();
            var idCus = "GS" + random.Next(1,  9+ random.Next(10, 90));

            var checkMail = db.KhachHangs.FirstOrDefault(s => s.Email == khachHang.Email);

            if (checkMail != null)
            {
                ModelState.AddModelError(string.Empty, "Đã có email trong hệ thống !!!");
            }

            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(khachHang.HoTenKH) == true ||
                    khachHang.NgaySinh == null ||
                    string.IsNullOrEmpty(khachHang.DiaChi) == true ||
                    string.IsNullOrEmpty(khachHang.Email) == true)
                {
                    TempData["trong"] = "Vui lòng nhập đầy đủ thông tin";
                    return View();
                }
                else
                {
                    khachHang.MaKH = idCus;
                    khachHang.MaLoaiKH = "TH";
                    khachHang.Username = null;
                    khachHang.UserPassword = null;
                    khachHang.HinhDaiDien = null;
                    khachHang.TongTienDat = null;
                    
                    db.KhachHangs.Add(khachHang);
                    db.SaveChanges();
                    //UserLogedInSingleton<KhachHang>.Instance.UpdateSigleton(db);
                }
            }
            return RedirectToAction("CreateOrder");
        }

        public JsonResult CheckEmailAvailability(string mail)
        {
            System.Threading.Thread.Sleep(200);

            var mailCus = db.KhachHangs.Where(x => x.Email == mail).SingleOrDefault();
            if (mailCus != null)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }

        public JsonResult CheckNoPhoneAvailability(string noPhone)
        {
            System.Threading.Thread.Sleep(200);

            var checkNoPhone = db.KhachHangs.Where(x => x.SDT == noPhone).SingleOrDefault();
            if (checkNoPhone != null)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }
        [HttpGet]
        public ActionResult GetInfoTour(string id)
        {
            // Lấy thông tin tương ứng với id từ CSDL
            var infoTour = db.Tours.Find(id);
            if (infoTour == null)
            {
                return Json(0, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(infoTour.SoChoNull, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult CreateOrder()
        {
            ViewBag.MaTour = new SelectList(db.Tours, "MaTour", "TenTour");
            return View();
        }
        [HttpPost]
        public ActionResult CreateOrder(BookTour donHang)
        {
            Random random = new Random();
            var maDH = "DH" + random.Next(1, 9)+ random.Next(10, 50)+ random.Next(51, 99);
            var user = (Tourist_VietripInsum_2023.Models.NhanVien)HttpContext.Session["user"];
            if (ModelState.IsValid)
            {
                if (donHang.MaTour == null)
                {
                    TempData["ErrorTour"] = "Vui lòng chọn tour!!!";
                    return RedirectToAction("CreateOrder");
                }
                if (donHang.SoCho < 1 || donHang.SoCho == null)
                {
                    TempData["ErrorSoCho"] = "Số chỗ phải lớn hơn 1!!!";
                    return RedirectToAction("CreateOrder");
                }
                var tour = db.Tours.Find(donHang.MaTour);
                if (donHang.SoCho > tour.SoChoNull)
                {
                    TempData["ErrorSoChoMax"] = "Số chỗ vượt quá số chỗ còn trống";
                    return RedirectToAction("CreateOrder");
                }
                else
                {
                    donHang.MaDH = maDH;
                    Session["MaDH"] = donHang.MaDH;
                    donHang.MaNVLap = user.MaNV;
                    donHang.NgayLap = System.DateTime.Now;

Tourist_VietripInsum_2023/Views/OrderProcessing/AddTicket.cshtml
@model Tourist_VietripInsum_2023.Models.Ve

@{
    ViewBag.Title = "AddTicket";
    Layout = "~/Views/OrderProcessing/LayoutOP/_ViewOP.cshtml";
}

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        @using (Html.BeginForm("AddTicket", "OrderProcessing", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class="modal-content">
                @{
                    var ve = db.Ves.FirstOrDefault();
                }
                <div class="modal-body" style="padding:20px 10px;">
                    @Html.HiddenFor(model => ve.MaDH)
                    @Html.HiddenFor(model => ve.MaVe)
                    <h4 style="text-align:center">THÊM VÉ</h4>
                    <input name="madh" value="@Model.MaDH" style="visibility:hidden" />
                    <div id="datve" class="datve" style="padding:0px 10px;"></div>

                    <div>
                        <button id="themve" onclick="ThemVe()" class="btn btn-success btn-sm">Thêm vé</button>
                        <button id="xoave" onclick="xoaVe()" class="btn btn-danger btn-sm">Xóa vé</button>
                    </div>
                </div>
                <input name="soluongdat" id="soluongdat" style="visibility:hidden" />
                <div class="modal-footer">
                    <button type="button" class="btn btn-warning btn-sm" data-dismiss="modal">Close</button>
                    <input type="submit" value="Thêm vé" class="btn btn-success btn-sm" />
                </div>
            </div>
        }
    </div>

</div>
<script>
    var i = 0;
    function ThemVe() {
        var ticketrow = document.createElement('div');
        ticketrow.classList.add('datve')
        var cartitem = document.getElementsByClassName("datve")[0];
        
        if (i < 5) {
            i++;
            var row = `<div class="ticket-info" id="nd` + i + `">` +

                `<div class="row" id="ListInfoAdult">` +
                `<div class="form-group group-info-name col-md-7">` +
                    `<span>Họ tên</span>` +
                    `<input class="form-control" name="Hoten_KH` + i + `" placeholder="Vui lòng nhập Họ tên" required="required" type="text" value="">` +
                `</div>` +
                `<div class="form-group col-md-5">` +
                    `<span>Loại vé</span>` +
                    `<select class="form-control col-sm-12" id="MaLVe' + i + '" name="MaLVe` + i + `">` +
                        `<option value="">Chọn loại vé</option>` +
                        `<option value="TICKET01">Vé người lớn</option>` +
                        `<option value="TICKET02">Vé trẻ em</option>` +
                    ` </select>` +
                ` </div>` +
                ` <div class="form-group group-info-sex col-sm-6">` +
                    `<span>Giới tính</span>` +
                    `<select class="form-control col-sm-12" id="GioiTinh' + i +'" name="GioiTinh` + i + `">` +
                        `<option value="">Giới tính</option>` +
                        `<option value="Nam">Nam</option>` +
                        `<option value="Nữ">Nữ</option>` +
                    `</select>` +
                `</div>` +
                `<div class="form-group group-info-birthday col-sm-6">` +
                    `<span>Ngày sinh</span>` +
                    `<input class="form-control text-box single-line" required="required" name="NgaySinh` + i + `" id="NgaySinh' + i +'" placeholder="Vui lòng nhập chọn ngày sinh"type="date" value="">` +
                `</div>` +
                `<div class="form-group group-info-note col-sm-12">` +
                    `<span>Lưu ý</span>` +
                    `<input class="form-control col-sm-12" name="LuuY` + i + `" id="LuuY' + i +'" placeholder="Nhập lưu ý" type="text" value="">` +
                `</div>` +
                `<p>-----</p>` +
                ` </div>` +
                ` </div>` +
                ` </div> `
                ;
            //var div = document.getElementById("datve");
            //div.innerHTML += row;
            ticketrow.innerHTML = row;
            cartitem.append(ticketrow);
            document.getElementById("soluongdat").value = i;
        };
    }
    function xoaVe() {
        var element = document.getElementById("datve");
        if (i > 1) {
            document.getElementById('nd' + i).remove();
            i--;
        }
        else {
            alert("soluong")
        }
        document.getElementById("soluongdat").value = i;

    }

</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Ve</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaVe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaVe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaVe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaDH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaDH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaDH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLVe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaLVe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaLVe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hoten_KH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hoten_KH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hoten_KH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LuuY, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LuuY, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LuuY, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Tourist_VietripInsum_2023/Views/OrderProcessing/CheckCusInfo.cshtml
@model Tourist_VietripInsum_2023.Models.KhachHang
@{
    ViewBag.Title = "Kiểm tra thông tin khách hàng";
    Layout = "~/Views/OrderProcessing/LayoutOP/_ViewOP.cshtml";
    ViewBag.Name = "Trang Kiểm Tra Thông Tin Khách Hàng";
    ViewBag.order = "active";
}

<div class="row">
    <div class="col-sm-12">
        <div class="tile">
            <h3 class="tile-title" style="text-align: center;">THÔNG TIN KHÁCH HÀNG</h3>
            <div class="tile-body">
                <div class="row">
                    <div class="row element-button">
                        <div style="text-align: center;">
                            <form method="get" style="margin: auto; width: 550px;">
                                <div style="display: flex; ">
                                    <label class="control-label" style="margin: auto 0; margin-right: 20px; padding: 5px 10px;">Số điện thoại</label>
                                    @if (ViewBag.SDT == null)
                                    {
                                        <input class="form-control btn-sm" style="" type="search" name="search" placeholder="Nhập số điện thoại" value="@Session["SDT"]" />
                                    }
                                    else
                                    {
                                        <input class="form-control btn-sm" type="search" name="search" value="@Session["SDT"]" />
                                    }
                                    <input class="btn btn-success" style="margin-left: 20px;" type="submit" value="Kiểm tra" />
                                </div>
                            </form>
                        </div>
                    </div>
                    @{ var sdt = ViewBag.SDT;}
                    <form method="post" enctype="multipart/form-data" action="/OrderProcessing/CheckCusInfo" style="width: 100%;">
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => sdt, new { htmlAttributes = new { @class = "form-control" } })
                        <div class="element-button">
                            <div class="row">
                                @if (TempData["trong"] != null)
                                {
                                    <div class="row">
                                        <div class="col-md-12">
                                            <b style="color: red;">@TempData["trong"]</b>
                                        </div>
                                    </div>
                                }
                                <div class="form-group col-md-5">
                                    <label class="control-label" style="margin-top: 20px;">Họ và tên</label>
                                    @Html.EditorFor(model => model.HoTenKH, new { htmlAttributes = new { @class = "form-control col-md-12" } })
                                    @Html.ValidationMessageFor(model => model.HoTenKH, "", new { @class = "text-danger" })
                                </div>

                                <div class="form-group col-md-4">
                                    <label class="control-label" style="margin-top: 20px;">Ngày sinh</label>
                                    @Html.TextBoxFor(model => model.NgaySinh, "{0:dd-MM-yyyy}", new { @class = "form-control col-md-12", type = "datetime" })
                                    @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
                                </div>

                                <div class="form-group col-md-3">
                                    <label class="control-label" style="margin-top: 20px;">Giới tính</label>
                                    <select class="form-control" id="GioiTinh" name="GioiTinh">
                                        <option>Nam</option>
                                        <option>Nữ</option>
                                    </select>
                                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label class="control-label">Địa chỉ</label>
                                    @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control col-md-12" } })
                                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                                </div>

                                <div class="form-group col-md-6">
                                    <label class="control-label">Email</label>
                                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control col-md-12", @id = "Email", onchange = "EmailCheck()" } })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                    <span id="mess"></span>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <a class="btn btn-cancel btn-sm" href="/OrderProcessing/ManageTourOrders">Quay lại</a>
                                @if (ViewBag.Info == null)
                                {
                                    <input type="submit" value="Tiếp tục" class="btn btn-success btn-sm" />
                                }
                                else
                                {
                                    <a class="btn btn-success btn-sm" href="/OrderProcessing/CreateOrder">Tiếp tục</a>
                                }
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="Scripts/jquery-1.4.1.js" type="text/javascript"></script>
<script type="text/javascript">
    function EmailCheck() {
        $("#mess").html("check ...");
        $.post("@Url.Action("CheckEmailAvailability", "OrderProcessing")",
            {
                mail: $("#Email").val()
            },
            function (data) {
                if (data == 0) {
                    $("#mess").html('<font color="Green">Available!</font>');
                    $("#Email").css("border-color", "Green");
                }
                else {
                    $("#mess").html('<font color="Red">Email này đã tồn tại</font>');
                    $("#Email").css("border-color", "Red");
                }
            }
        )
    }
</script>

Tourist_VietripInsum_2023/Views/OrderProcessing/CreateOrder.cshtml
@model Tourist_VietripInsum_2023.Models.BookTour
@using Tourist_VietripInsum_2023.Models
@{
    ViewBag.Title = "Đặt tour";
    Layout = "~/Views/OrderProcessing/LayoutOP/_ViewOP.cshtml";
    ViewBag.Name = "Trang Đặt Tour";
    ViewBag.order = "active";

    TouristEntities1 db = new TouristEntities1();
    var tour = db.Tours.ToList();
}
@if (TempData["ErrorSoCho"] != null)
{
    <script>
        swal({
            title: "@TempData["ErrorSoCho"]",
            icon: "warning",
            button: "Thoát",
        });
    </script>
}
@if (TempData["ErrorTour"] != null)
{
    <script>
        swal({
            title: "Vui lòng chọn tour",
            icon: "warning",
            button: "Thoát",
        });
    </script>
}
@if (TempData["ErrorSoChoMax"] != null)
{
    <script>
        swal({
            title: "Số chỗ vượt quá số chỗ còn trống",
            icon: "warning",
            button: "Thoát",
        });
    </script>
}
@if (TempData["ErrorSoChoTrong"] != null)
{
    <script>
        swal({
            title: "Số chỗ vượt quá số chỗ còn trống",
            icon: "warning",
            button: "Thoát",
        });
    </script>
}

<div class="row">
    <div class="col-sm-12">
        <div class="tile">
            <h3 class="tile-title" style="text-align: center;">ĐẶT TOUR</h3>
            <div class="tile-body">
                <div class="row">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="row element-button">
                            <div class="form-group col-md-8">
                                <label class="control-label">Tên tour</label>
                                @*@Html.DropDownList("MaTour", null, htmlAttributes: new { @class = "form-control col-sm-12" })*@
                                <select class="form-control col-sm-12" id="MaTour" name="MaTour">
                                    <option value="">Vui lòng chọn tour</option>
                                    @foreach (var item in tour)
                                    {
                                        if (item.TrangThai != "Sắp ra mắt")
                                        {
                                            <option value="@item.MaTour">@item.TenTour</option>
                                        }
                                    }
                                </select>
                                @*@Html.DropDownListFor(m => m.MaTour, (SelectList)ViewBag.MaTour, "Vui lòng chọn tour", htmlAttributes: new { @class = "form-control col-sm-12" })*@
                                @Html.ValidationMessageFor(model => model.MaTour, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group col-md-4">
                                <label class="control-label">Số chỗ trống</label>
                                <span class="form-control" id="SoChoNull" type="number">0</span>
                            </div>
                            <div class="form-group col-md-4">
                                <label class="control-label">Số điện thoại</label>
                                @Html.EditorFor(model => Session["SDT"], new { htmlAttributes = new { @class = "form-control col-sm-12", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.SdtKH, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group col-md-4">
                                <label class="control-label">Số lượng vé</label>
                                @Html.EditorFor(model => model.SoCho, new { htmlAttributes = new { @class = "form-control col-sm-12", @id = "numberplace" } })
                                @Html.ValidationMessageFor(model => model.SoCho, "", new { @class = "text-danger" })
                                <span class="text-secondary"> * Vé chưa bao gồm người đặt!</span>
                            </div>
                            <div class="form-group col-md-4">
                                <label class="control-label">Hình thức thanh toán</label>
                                <select class="form-control list-box tri-state" id="HinhThucThanhToan" name="HinhThucThanhToan">
                                    <option selected="selected" value="true">Chuyển khoản</option>
                                    <option value="false">Tiền mặt</option>
                                </select>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <a class="btn btn-cancel btn-sm" href="/OrderProcessing/CheckCusInfo/ManageTourOrders">Quay lại</a>
                                <input type="submit" value="Tiếp tục" class="btn btn-success btn-sm" />
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="Scripts/jquery-1.4.1.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#MaTour').change(function () {
            var id = $(this).val();

            $.ajax({
                url: '/OrderProcessing/GetInfoTour',
                type: 'GET',
                data: { id: id },
                success: function (data) {
                    $('#SoChoNull').html(data);
                }
            });
        });
    });
</script>