Tourist_VietripInsum_2023/Controllers/TourmanagerController.cs
using Microsoft.Build.Framework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Windows.Controls;
using Tourist_VietripInsum_2023.App_Start;
using Tourist_VietripInsum_2023.DesignPattern.TemplateMethod;
using Tourist_VietripInsum_2023.Models;

namespace Tourist_VietripInsum_2023.Controllers
{
    [AdminAuthorize(idPos = "TM")]
    public class TourmanagerController : TemplateMethodController
    {
        private TouristEntities1 db = new TouristEntities1();

        public TourmanagerController()
        {
            var result = PrintInfo();
            Debugger.Log(1,"Logger: ",$"{result}");
        }


        // GET: Tourmanager

        public ActionResult HomePageTM()
        {
            var totalT = 0;
            totalT = db.Tours.ToList().Count;
            TempData["tongTour"] = totalT;
            var totalTT = 0;
            totalTT = db.LoaiTours.ToList().Count;
            TempData["tongLT"] = totalTT;
            var totalDD = 0;
            totalDD = db.DiaDiemThamQuans.ToList().Count;
            TempData["tongDD"] = totalDD;
            var totalTinh = 0;
            totalTinh = db.TinhThanhs.ToList().Count;
            TempData["tongTinh"] = totalTinh;
            return View(db.Tours.ToList());
        }

        //        // GET: Tours
        //        //Trang hiển thị danh sách loại tour, hotel, tour
        public ActionResult QuanLyTour()
        {
            List<Tour> listTour = db.Tours.Include(t => t.LoaiTour).ToList();
            //var tours = db.Tours.ToList().OrderByDescending(s => s.IdTour);
            return View(listTour);
        }

        //        //search view
        [HttpPost]
        public ActionResult QuanLyTour(string option, string search)
        {

            //if a user choose the radio button option as Subject  
            if (option == "IDTour")
            {
                //Index action method will return a view with a student records based on what a user specify the value in textbox  
                return View(db.Tours.Where(x => x.MaTour.StartsWith(search) || search == null).ToList());
            }
            else if (option == "Tourname")
            {
                return View(db.Tours.Where(x => x.TenTour.StartsWith(search) || search == null).ToList());
            }
            else
            {
                return View(db.Tours.Where(x => x.SoChoNull.Equals(search) || search == null).ToList());
            }
        }

        public ActionResult CusDetailsTour(string id)
        {
            TempData["MaTour"] = id;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            List<BookTour> booking = db.BookTours.Where(s => s.MaTour == id && s.TrangThaiTT == true).ToList();
            List<Ve> ve = new List<Ve>();
            foreach (var i in booking)
            {
                var maDH = i.MaDH;
                ve = db.Ves.Where(s => s.MaDH == maDH).ToList();
            }
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(ve);
        }

        //Hotel
        public ActionResult HotelManager()
        {
            ViewBag.MaTinh = new SelectList(db.TinhThanhs, "MaTinh", "TenTinh");
            var hotels = db.Hotels.Include(h => h.TinhThanh);
            return View(hotels.ToList());
        }

        // GET: Hotels/Create
        //public ActionResult CreateHotel()
        //{
        //    ViewBag.MaTinh = new SelectList(db.TinhThanhs, "MaTinh", "TenTinh");
        //    return View();
        //}

        // POST: Hotels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult CreateHotel(Hotel newks,string Matinh,string TenKS,string Sao)
        {
            if (ModelState.IsValid)
            {

                Random rd = new Random();
                newks.MaKS = "KS" + rd.Next(1000);
                newks.MaTinh = Matinh;
                newks.TenKS = TenKS;
                newks.Sao = Sao;
                db.Hotels.Add(newks);
                db.SaveChanges();
                TempData["noti"] = "taokhachsan";
                return RedirectToAction("HotelManager");
            }

            ViewBag.MaTinh = new SelectList(db.TinhThanhs, "MaTinh", "TenTinh", newks.MaTinh);
            return View(newks);
        }

        // GET: Hotels/Edit/5
        public ActionResult EditHotel(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.Hotels.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaTinh = new SelectList(db.TinhThanhs, "MaTinh", "TenTinh", hotel.MaTinh);
            return View(hotel);
        }

        // POST: Hotels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditHotel([Bind(Include = "MaKS,MaTinh,TenKS,Sao")] Hotel hotel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hotel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("HotelManager");
            }
            ViewBag.MaTinh = new SelectList(db.TinhThanhs, "MaTinh", "TenTinh", hotel.MaTinh);
            return View(hotel);
        }

        [HttpPost]
        public ActionResult DeleteHotel(string id, Hotel ht)
        {
            ht = db.Hotels.Where(s => s.MaKS == id).FirstOrDefault();
            TempData["noti"] = "delete-true";
            db.Hotels.Remove(ht);
            db.SaveChanges();
            return RedirectToAction("HotelManager");
        }
        //End hotel

        // Phuong tien
        //public ActionResult CreateTrans()
        //{
        //    return View();
        //}

        //[HttpPost]
        public ActionResult CreateTrans(PhuongTien trans,string TenPTien,string HangXe,string Chitiet)
        {
            if (!ModelState.IsValid)
            {
                return View(trans);
            }
            Random rd = new Random();
            var idTrans = "PT" + rd.Next(1, 1000);
            trans.MaPTien = idTrans;
            trans.TenPTien = TenPTien;
            trans.HangXe = HangXe;
            trans.ChiTiet = Chitiet;

            db.PhuongTiens.Add(trans);
            TempData["noti"] = "addtrans";
            db.SaveChanges();
            return RedirectToAction("HotelManager");

        }

        public ActionResult EditTrans(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhuongTien transport = db.PhuongTiens.Find(id);
            if (transport == null)
            {
                return HttpNotFound();
            }
            return View(transport);
        }

        [HttpPost]
        public ActionResult EditTrans(PhuongTien transport)
        {
            if (ModelState.IsValid)
            {
                TempData["noti"] = "edittrans";
                db.Entry(transport).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("HotelManager");
            }
            return View(transport);
        }
        [HttpPost]
        public ActionResult DeleteTrans(string id, PhuongTien trans)
        {

            trans = db.PhuongTiens.Where(s => s.MaPTien == id).FirstOrDefault();
            var detail = db.ChiTietTours.ToList();
            var count = 0;
            for (int i = 0; i < detail.Count; i++)
            {
                if (trans.MaPTien == detail[i].MaPTien)
                {
                    count++;
                }
            }
            if (count > 0)
            {
                TempData["noti"] = "deletetrans-false";
                return RedirectToAction("HotelManager");
            }
            else
            {
                TempData["noti"] = "deletetrans-true";
                db.PhuongTiens.Remove(trans);
                db.SaveChanges();
                return RedirectToAction("HotelManager");
            }
        }

        [HttpPost]
        public ActionResult DuplicateTrans(string id, PhuongTien trans)
        {

            trans = db.PhuongTiens.Where(s => s.MaPTien == id).FirstOrDefault();
            PhuongTien newTrans = (PhuongTien)trans.Clone();

            db.PhuongTiens.Add(newTrans);
            TempData["noti"] = "duplicatetrans";
            db.SaveChanges();
            return RedirectToAction("HotelManager");
        }
        //end phuong tien
        //---------------------------------------------------------------//
        // Dia diem tham quan
        public ActionResult LocationManager()
        {
            var lc = db.DiaDiemThamQuans.Include(d => d.TinhThanh);
            return View(lc.ToList());
        }


        public ActionResult VistLocationsDetails(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DiaDiemThamQuan diaDiemThamQuan = db.DiaDiemThamQuans.Find(id);
            if (diaDiemThamQuan == null)
            {
                return HttpNotFound();
            }
            return View(diaDiemThamQuan);
        }

Tourist_VietripInsum_2023/Views/Tourmanager/CreateHotel.cshtml
@model Tourist_VietripInsum_2023.Models.Hotel

@{
    ViewBag.Title = "CreateHotel";
    Layout = "~/Views/Tourmanager/LayoutTM/_ViewTM.cshtml";
    ViewBag.Name = "Hotel Manager";
    ViewBag.qlt = "active";
}

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="tile">
            <h4 class="tile-title"> CREATE NEW HOTEL</h4>
            <div class="tile-body">
                @using (Html.BeginForm("CreateHotel", "Tourmanager"))
                {
                    @Html.AntiForgeryToken()
                    <div class="container">


                        <div class="form-horizontal">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.MaKS)
                            <div class="row">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.MaTinh, "MaTinh", htmlAttributes: new { @class = "control-label col-md-12" })
                                    <div class="col-md-12">
                                        @Html.DropDownList("MaTinh", null, htmlAttributes: new { @class = "form-control col-md-12" })
                                        @Html.ValidationMessageFor(model => model.MaTinh, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.TenKS, htmlAttributes: new { @class = "control-label col-md-12" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.TenKS, new { htmlAttributes = new { @class = "form-control col-md-12" } })
                                        @Html.ValidationMessageFor(model => model.TenKS, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Sao, htmlAttributes: new { @class = "control-label col-md-12" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.Sao, new { htmlAttributes = new { @class = "form-control col-md-12" } })
                                        @Html.ValidationMessageFor(model => model.Sao, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                            </div>
                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" value="Create Hotel" class="btn btn-success btn-sm" />
                                    <a class="btn btn-warning" href="/Tourmanager/HotelManager"> Trở lại</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="col-md-3"></div>
</div>

Tourist_VietripInsum_2023/Views/Tourmanager/CreateVisitLocations.cshtml
@model Tourist_VietripInsum_2023.Models.DiaDiemThamQuan

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Tourmanager/LayoutTM/_ViewTM.cshtml";
}

<div class="col-md-12">
    <div class="tile">
        <h4 class="tile-title"> CREATE NEW VISIT LOACATION</h4>
        <div class="tile-body">
            @using (Html.BeginForm("CreateVisitLocations", "Tourmanager", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="row">
                    <div class="col-sm-1" style="border-right: 6px solid black;">
                        <h4 style="writing-mode: vertical-rl;"> </h4>
                    </div>
                    <div class="col-sm-5">
                        <div class="form-group col-12">
                            <div style="width: 100%; height: auto; border: 2px solid red; padding: 10px; border-radius: 50px 20px;">
                                <br />
                                @*@Html.TextBox("ImagerVis", "", new { type = "file", @class = "fas fa-cloud-upload-alt" })*@
                                @Html.TextBox("ImagerVis", "", new { type = "file" })
                                <br />
                                <br />
                                <img id="preview" src="#" width="100%" height="auto" style="visibility: hidden; border: 4px outset; margin-bottom:20px;" />

                            </div>
                        </div>
                    </div>

                    <div class="col-sm-5">
                        <div class="form-group">
                            @Html.LabelFor(model => model.MaTinh, "MaTinh", htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-12">
                                @Html.DropDownList("MaTinh", null, htmlAttributes: new { @class = "form-control col-md-12" })
                                @Html.ValidationMessageFor(model => model.MaTinh, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.TenDDTQ, htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.TenDDTQ, new { htmlAttributes = new { @class = "form-control col-md-12" } })
                                @Html.ValidationMessageFor(model => model.TenDDTQ, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-12">
                                @Html.TextAreaFor(model => model.MoTa, new { @class = "form-control content-editor col-md-12" })
                                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control col-md-12" } })
                                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-outline-danger" />
                                <a class="btn btn-outline-success" href="/Tourmanager/LocationManager">Back to list</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-1" style="border-left: 6px solid black;">
                        <h4 style="writing-mode: vertical-rl;"></h4>
                    </div>
                </div>
            }

        </div>
    </div>
</div>
<script>
    ImagerVis.onchange = evt => {
        const [file] = ImagerVis.files
        if (file) {
            preview.src = URL.createObjectURL(file);
            document.getElementById("preview").style.visibility = "visible";
        }
    }
</script>

Tourist_VietripInsum_2023/Views/Tourmanager/IndexLoaiTour.cshtml
@model IEnumerable<Tourist_VietripInsum_2023.Models.LoaiTour>

@{
    ViewBag.Title = "IndexLoaiTour";
    Layout = "~/Views/Tourmanager/LayoutTM/_ViewTM.cshtml";
    ViewBag.Name = "Tour Manager";
    ViewBag.qlt = "active";
}
<div class="row">
    <div class="col-sm-8">
        <div class="tile">
            <h2 class="tile-title">Danh sách loại tour</h2>

            <a class="btn btn-sm btn-add " type="button" title="CreateTour" href="/Tourmanager/CreateLoaiTour">
                <i class="fas fa-plus"> </i> Tạo mới
            </a>
            <table class="table table-hover table-bordered js-copytextarea dataTable no-footer" cellpadding="0" cellspacing="0" border="0" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                <thead>
                    <tr>
                        <th>Mã loại</th>
                        <th>
                            Tên loại
                        </th>
                        <th>
                            Chiết khấu
                        </th>
                        <th>
                            Tùy chọn
                        </th>
                    </tr>
                </thead>


                @foreach (var item in Model)
                {
                    <tr >
                        <td class="text-center">
                            @Html.DisplayFor(modelItem => item.MaLTour)
                        </td>
                        <td class="text-center">
                            @Html.DisplayFor(modelItem => item.TenLTour)
                        </td>
                        <td class="text-center">
                            @Html.DisplayFor(modelItem => item.ChietKhau)
                        </td>
                        <td class="text-center">
                            <a class="btn btn-cancel" title="Edit" href="~/Tourmanager/EditLoaiTour/@item.MaLTour">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a class="btn btn-excel" ata-toggle="tooltip" title="Delete" data-target="#DeleteModal-@item.MaLTour" data-toggle="modal">
                                <i class="fas fa-trash"></i>
                            </a>
                            @using (Html.BeginForm("DeleteLoaiTour/" + item.MaLTour, "Tourmanager", FormMethod.Post, null))
                            {
                                @Html.AntiForgeryToken()
                                <div class="modal" tabindex="-1" role="dialog" id="DeleteModal-@item.MaLTour">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title">Delete Confirmation</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <p>Are you sure you want to delete this customer?</p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                                                <button type="submit" class="btn btn-danger">Yes</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </td>
                    </tr>
                }

            </table>
            <a class="btn btn-cancel" title="Trở lại" href="~/Tourmanager/QuanLyTour">
                Trở lại
            </a>
        </div>
    </div>
    <div class="col-sm-4">
        <img src="~/images/green_typetour.gif" height="95%" width="100%" quality="high"/>
    </div>
</div>


<script>

        function OpenDeleteModal() {
            $("#myModalHotel").modal('show');

    }

        function DeleteHotel() {
        var data = document.getElementById("a").innerHTML;
        alert(data);
        //$.ajax(
        //    {
            //        type: 'GET',
            //        url: '/Home/Delete',
            //        contentType: 'application/json; charset=utf=8',
            //        data: data,
            //        success: function (result) {
            //            $('#modal-delete-content').html(result);
            //            $('#modal-delete').modal('show');
            //        },
            //        error: function (er) {
            //            alert(er);
            //        }
            //    });
        }

</script>

Tourist_VietripInsum_2023/Views/Tourmanager/LocationManager.cshtml
@model IEnumerable<Tourist_VietripInsum_2023.Models.DiaDiemThamQuan>

@{
    ViewBag.Title = "LocationManager";
    Layout = "~/Views/Tourmanager/LayoutTM/_ViewTM.cshtml";
    ViewBag.Name = "Location Manager";
    ViewBag.dh = "active";

}

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@{
    var checkdata = TempData["noti"];
    if (checkdata == "edit")
    {
        <script>
            swal("Good job!", "You have successfully edited the hotel information!", "success");
        </script>
    }
    else if (checkdata == "add")
    {
        <script>
            swal("Good job!", "You have created hotel information!", "success");
        </script>
    }
    if (checkdata == "deletetrans-false")
    {
        <script>
            swal("Warning!", "The transport is being used in the current tour!!!", "warning")
        </script>
    }
    else if (checkdata == "deletetrans-true")
    {
        <script>
            swal("Good job!", "You deleted the transport!", "success");
        </script>
    }

}

<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <h2 class="tile-title">Các điểm tham quan</h2>
            <div class="tile-body">
                <div class="row" style="padding:10px">
                    <div class="col-sm-2 element-button">
                        <a class="btn btn-success btn-sm " type="button" title="New VisitLocation" href="/Tourmanager/CreateVisitLocations">
                            Add more location
                        </a>
                    </div>
                </div>
                <div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-hover table-bordered js-copytextarea dataTable no-footer" cellpadding="0" cellspacing="0" border="0" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                                @*//Phần render từng dòng trong C#*@
                                <thead style="background-color: #ffd43b;">
                                    <tr>
                                        <th aria-controls="sampleTable" rowspan="1" colspan="1">Mã</th>
                                        <th aria-controls="sampleTable" rowspan="1" colspan="1" width="90px">Tên địa điểm</th>
                                        <th aria-controls="sampleTable" rowspan="1" colspan="1" width="100px">Hình minh họa</th>
                                        <th aria-controls="sampleTable" rowspan="1" colspan="1" width="120px">Địa chỉ</th>
                                        <th aria-controls="sampleTable" rowspan="1" colspan="1" width="80px">Tỉnh thành</th>
                                        <th aria-controls="sampleTable" rowspan="1" colspan="1">Mô tả</th>
                                        <th aria-controls="sampleTable" rowspan="1" colspan="1">Chức năng</th>

                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model)
                                    {

                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.MaDDTQ)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.TenDDTQ)
                                        </td>
                                        <td>
                                            <img src="@item.HinhMinhHoa_D" width="100px" height="100px" />
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.DiaChi)
                                        </td>
                                        <td>

                                            @Html.DisplayFor(modelItem => item.TinhThanh.TenTinh)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.MoTa)
                                            
                                        </td>
                                        <td style="text-align:center">
                                            <a href="/Tourmanager/EditVisitLocations/@item.MaDDTQ" class="btn btn-outline-primary btn-sm" ata-toggle="tooltip" title="Edit">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            @*<a href="/Tourmanager/VistLocationsDetails/@item.MaDDTQ" class="btn btn-outline-primary btn-sm" ata-toggle="tooltip" title="Detail">
                                                <i class="fas fa-train"></i>
                                            </a>*@
                                            <a class="btn btn-outline-primary btn-sm" ata-toggle="tooltip" title="Delete" data-target="#DeleteModalTrans-@item.MaDDTQ" data-toggle="modal">
                                                <i class="fas fa-trash"></i>
                                            </a> 
                                            @using (Html.BeginForm("DeleteVisitLocations/" + item.MaDDTQ, "Tourmanager", FormMethod.Post, null))
                                            {
                                                @Html.AntiForgeryToken()
                                                <div class="modal" tabindex="-1" role="dialog" id="DeleteModalTrans-@item.MaDDTQ">
                                                    <div class="modal-dialog" role="document">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h5 class="modal-title">Delete Confirmation</h5>
                                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                    <span aria-hidden="true">&times;</span>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body">
                                                                <p>Are you sure you want to delete this VISIT LOCATION?</p>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                                                                <button type="submit" class="btn btn-danger">Yes</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            }
                                        </td>
                                    </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>